// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portal.Core.Data;

namespace RneSniffer.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201030145335_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("RneSniffer.Core.EntrepriseRne", b =>
                {
                    b.Property<string>("IdentifiantUnique")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdresseSiege")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdresseSiegeArabe")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnneeCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("BureauRegional")
                        .HasColumnType("TEXT");

                    b.Property<string>("BureauRegionalArabe")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("DenominationSociale")
                        .HasColumnType("TEXT");

                    b.Property<string>("DenominationSocialeArabe")
                        .HasColumnType("TEXT");

                    b.Property<string>("EtatRegistre")
                        .HasColumnType("TEXT");

                    b.Property<string>("EtatRegistreArabe")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormeJuridique")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormeJuridiqueArabe")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibelleActivite")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibelleActiviteArabe")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomCommercial")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomCommercialArabe")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomResponsable")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomResponsableArabe")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrenomResponsable")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrenomResponsableArabe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionArabe")
                        .HasColumnType("TEXT");

                    b.Property<string>("SituationFiscale")
                        .HasColumnType("TEXT");

                    b.Property<string>("SituationFiscaleArabe")
                        .HasColumnType("TEXT");

                    b.HasKey("IdentifiantUnique");

                    b.ToTable("EntrepriseRne");
                });
#pragma warning restore 612, 618
        }
    }
}
